# name: deploy-orders

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'orders/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       - run: cd orders && docker build -t rallycoding/orders .
#       - run: docker push rallycoding/orders
#       - uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#       - run: doctl kubernetes cluster kubeconfig save ticketing
#       - run: kubectl rollout restart deployment orders-depl

name: Deploy Orders

on:
  push:
    branches:
      - master
    paths:
      - 'orders/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: aws-actions/amazon-ecr-login@v1
      - run: |
          docker build -t ${{ secrets.ECR_REPO }}/orders:${{ github.sha }} ./orders
          docker push ${{ secrets.ECR_REPO }}/orders:${{ github.sha }}
          aws eks update-kubeconfig --name ticketing-cluster --region ${{ secrets.AWS_REGION }}
          kubectl set image deployment/orders-depl orders=${{ secrets.ECR_REPO }}/orders:${{ github.sha }}
