# name: deploy-expiration

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'expiration/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#       - run: cd expiration && docker build -t rallycoding/expiration .
#       - run: docker push rallycoding/expiration
#       - uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#       - run: doctl kubernetes cluster kubeconfig save ticketing
#       - run: kubectl rollout restart deployment expiration-depl

name: Deploy Expiration

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v1

      - run: |
          docker build -t ${{ secrets.ECR_REPO }}/expiration:${{ github.sha }} ./expiration
          docker push ${{ secrets.ECR_REPO }}/expiration:${{ github.sha }}

      - run: |
          aws eks update-kubeconfig --name ticketing-cluster --region ${{ secrets.AWS_REGION }}
          kubectl set image deployment/expiration-depl expiration=${{ secrets.ECR_REPO }}/expiration:${{ github.sha }}
