# name: deploy-manifests

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'infra/**'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: digitalocean/action-doctl@v2
#         with:
#           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#       - run: doctl kubernetes cluster kubeconfig save ticketing
#       - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod

name: Deploy Infra Manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          aws eks update-kubeconfig --name ticketing-cluster --region ${{ secrets.AWS_REGION }}
          kubectl apply -f infra/k8s
          kubectl apply -f infra/k8s-prod
